### PR TITLE
3-stable per session_last_update

### PR DESCRIPTION
**Pull request by coppermind**
Hey @nickgrim, I moved this PR to a new branch.

* `3.8.0` is not a clean merge this time compared to `3.6.0` but should still be relatively painless.
* `magic_columns.rb` is updated with just the minimum required modification for the updated method `#last_request_update_allowed?` in `abstract_adapter.rb`
* tested for `5.1.7` and now getting all green

### CODE REVIEW

**Comment by nickgrim** [comment]
> 3.8.0 is not a clean merge this time compared to 3.6.0 but should still be relatively painless.

Sure: that's to be expected because of the refactoring that's happened between the `liveminds` fork and the `coppermind` fork. Obviously we're not going to _merge_ it though, so that won't be a problem. :)

**Review by nickgrim — APPROVED** [review]
I'm hitting Approve _here_, but only because Github doesn't have a "don't merge this, update the branch head instead" button.

**Comment by coppermind** [comment]
Heya @nickgrim, Just an FYI, I tested this on the current production version. All tests appear to be green with just deprecation notices for `authlogic`.

**Comment by nickgrim** [comment]
Excellent. I'm happy for you to go ahead and update the branch head in the `liveminds` repo. (Or I can do it, if you want)

**Pull request closed without merging**
